version: "3"
services:
  PPCF-BOT:
    container_name: PPCF-BOT
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ppcf-bot:latest
    environment:
     - DISCORD_TOKEN:${DISCORD_TOKEN}
    volumes:
     - /usr/src/app:${DB_PATH} 
