version: "3"
services:
  PPCF-BOT:
    container_name: PPCF-BOT
    build: .
    image: ppcf-bot:latest
    environment:
     DISCORD_TOKEN: ${DISCORD_TOKEN}
    volumes:
      - ${DB_PATH}:/usr/src/app/data.db
    restart: always
